project:
  type: website
  output-dir: docs

  render:
    - "*.qmd"
    - "*.ipynb"
    # - "!ignored.qmd"
    # - "!project/"
execute:
  freeze: auto

website:
  title: "Pavel Grigoryev projects"
  open-graph:
    locale: en_US
  navbar:
    left:
      - href: projects/index.qmd
        text: Projects

format:
  html:
    theme: flatly
    css: styles.css
    # toc: true


